
CREATE TABLE ENTRIES (
  index   INTEGER PRIMARY KEY,
  term    INTEGER,
  applied BOOLEAN,
  data    BLOB
);

CREATE TABLE CURRENT_TERM (
  term INTEGER
);

CREATE TABLE VOTED_FOR (
  id VARCHAR
);

INSERT INTO CURRENT_TERM (term) VALUES (0);
INSERT INTO VOTED_FOR (id) VALUES (NULL);
